<!doctype html>
<html lang="pt-br">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="icon" href="img/icon/favicon.png" />

    <title>ERRO</title>
</head>
<div class="bg-image" style="background-image: url('img/error/404.jpg');
            height: 100vh">
<body class="bg-secondary text-black">
    
        
            <h1 class="text-center">Essa página não foi encontrada</h1>
            <div class="text-center">
            <a href="/" class="btn btn-lg btn-primary">Retornar a página inicial</a>
            </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

</body>
</div>
</html>
