<div class="container">
    <main class="form-signin">
        <form class="form-signin" method="POST" action="/exec_authenticator">
            <img class="mb-4" src="img/login/food.png" alt="" width="158" height="158">
            <h1 class="h3 mb-3 fw-normal">Área de login</h1>
            <?php
            if (isset($_SESSION['msg'])) {
                echo $_SESSION['msg'];
                unset($_SESSION['msg']);
            }

            if (!isset($this->dados['formReturn'])) {
                $nome = $email = "";
            } else {
                extract($this->dados['formReturn']);
            }
            ?>
            <div class="form-floating">
                <input type="email" class="form-control" id="floatingInput" placeholder="nome@exemplo.com" name="email">
                <label for="floatingInput">Email</label>
            </div>
            <div class="form-floating">
                <input type="password" class="form-control" id="floatingPassword" placeholder="Senha" name="password">
                <label for="floatingPassword">Senha</label>
            </div>
            <button class="w-100 btn btn-lg btn-primary" type="submit">Logar</button>
            <p class="mt-5 mb-3 text-muted">© 2023</p>
        </form>
    </main>
</div>