<div class="container">
    <?php
    if (isset($_SESSION['msg'])) {
        echo $_SESSION['msg'];
        unset($_SESSION['msg']);
    }
    ?>
</div>
<title>Produtos</title>


<div class="container">
    <div class="row">
        <div class="col-12 col-md-5">
            <form class="justify-content-center justify-content-md-start mb-3 mb-md-0" action="/search" method="GET">
                <div class="input-group input-group-sm">
                    <input type="text" class="form-control" placeholder="procurar produto" name="search">
                    <button type="submit" class="btn btn-dark">buscar</button>
                </div>
            </form>
        </div>
        <div class="col-12 col-md-7">
            <div class="d-flex flex-row-reverse justify-content-center justify-content-md-start">
                <form class="ml-3 d-inline-block">
                    <select class="form-select form-select-sm">
                        <option>Ordenar pelo nome</option>
                        <option>Ordenar pelo menor preço</option>
                        <option>Ordenar pelo maior preço</option>
                    </select>
                </form>
                <nav class="d-inline-block">
                    <ul class="pagination pagination-sm my-0">
                        <li class="page-item">
                            <buttom class="page-link">1</buttom>
                        </li>
                        <li class="page-item">
                            <buttom class="page-link">2</buttom>
                        </li>
                        <li class="page-item">
                            <buttom class="page-link">3</buttom>
                        </li>
                        <li class="page-item">
                            <buttom class="page-link">4</buttom>
                        </li>
                        <li class="page-item">
                            <buttom class="page-link">5</buttom>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
    <hr class="mt-3">

    <div class="row">

        <?php
        if ($this->data == null) {
            echo "<div class=\"col-sm-6\">
                <h1>Nenhum produto encontrado an pesquisa</h1>
            </div>";
        }
        else {
        foreach ($this->data as $key) { ?>
            <div class="col-sm-6">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title"><?= $key->nome ?></h5>
                        <img src="img/product/<?= $key->imagem ?>" class="card-img-top" style="mx-height: 20px; max-height:300px;" alt="sorvete">
                        <p class="card-text"><?= $key->descricao ?></p>
                        <h5 class="card-title">R$<?= $key->preco ?></h5>
                    </div>
                </div>
            </div>
        <?php }} ?>

    </div>

    <hr class="mt-3">
</div>