<div style="display: flex;
    align-items: center;
    padding-top: 40px;
    padding-bottom: 40px;
    padding-left:50em"
    class="text-center"
    >
    <form class="form-signin" method="POST" action="/exec_register_product">
        <img class="mb-4" src="img/login/food.png" alt="" width="158" height="158">
        <h1 class="h3 mb-3 fw-normal">Cadastro de produto</h1>
        <?php
        if (isset($_SESSION['msg'])) {
            echo $_SESSION['msg'];
            unset($_SESSION['msg']);
        }

        if (!isset($this->dados['formReturn'])) {
            $nome = $email = "";
        } else {
            extract($this->dados['formReturn']);
        }
        ?>
        <div class="form-floating">
            <label for="floatingInput">Nome</label>
            <input type="text" class="form-control" id="floatingInput" placeholder="Nome" name="nome" required>
        </div>
        <div class="form-floating">
            <label for="floatingInput1">Descrição</label>
            <input type="text" class="form-control" id="floatingInput1" placeholder="Descrição" name="descricao" required>
        </div>
        <div class="form-floating">
            <label for="floatingInput3">Preço</label>
            <input type="float" class="form-control" id="floatingInput3" placeholder="Preço" name="preco" required>
        </div>
        <br>
        <button class="w-100 btn btn-lg btn-primary" type="submit">Cadastrar produto</button>
    </form>
</div>
